version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-chat-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=nest-chat-secret-key
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nest-chat-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
